[tool.poetry]
name = "fastapi-neon"
version = "0.1.0"
description = ""
authors = ["maaazahmed <maazahmeed2k16@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
